import { Inter, Manrope } from "next/font/google";
import "./globals.css";


const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-inter",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["800"],
  variable: "--font-manrope",
});

export const metadata = {
  title: "Gym Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          />
      </head>
      <body className={`${manrope.variable} ${inter.variable}`}>
        <header className="header">
          <div className="container">
              <nav className="navbar">
                  <a href="#" className="logo">
                      <span className="logo-icon">💪</span>
                      <span className="logo-text">ELEVATE</span>
                  </a>
                  
                  <input type="checkbox" id="menu-toggle" className="menu-toggle" />
                  <label htmlFor="menu-toggle" className="menu-button">
                      <span className="menu-line"></span>
                      <span className="menu-line"></span>
                      <span className="menu-line"></span>
                  </label>
                  
                  <ul className="nav-links">
                      <li><a href="#" className="nav-link active">Home</a></li>
                      <li><a href="#" className="nav-link">Programs</a></li>
                      <li><a href="#" className="nav-link">Pricing</a></li>
                      <li><a href="#" className="nav-link">About</a></li>
                      <li><a href="#" className="nav-link">Contact</a></li>
                      <li><a href="login.html" className="nav-link cta-nav">Login <i className="fas fa-arrow-right"></i></a></li>
                  </ul>
              </nav>
          </div>
      </header>
        {children}
      </body>
    </html>
  );
}
