name: CI

on:
  push:
    branches: ["main"]
  pull-request:
    branches["main"]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 24
      
      - name: Install backend dependencies
        run: npm install 
        working-directory: backend # point to specific folder

      - name: Run backend tests
        run: npm test
        working-directory: backend 